name: dvc-wordpress
services:
  # 開発コンテナー
  dvc-wordpress:
    # base image: hiro345g/dvc:202606
    image: dvc-wordpress:php-202606
    container_name: dvc-wordpress
    hostname: dvc-wordpress
    init: true
    tty: true
    user: node
    working_dir: /home/node/workspace
    networks:
      dvc-net:
    volumes:
      - type: volume
        source: node-local-share-mise
        target: /home/node/.local/share/mise
      - type: volume
        source: node-local-state-mise
        target: /home/vscode/.local/state/mise
      - type: volume
        source: workspace-data
        target: /home/node/workspace
      - type: volume
        source: vscode-server-extensions
        target: /home/node/.vscode-server/extensions
      - type: bind
        source: ${PROJECT_DIR:-.}
        target: /dvc-wordpress
        read_only: true
      - type: bind
        source: ${PROJECT_DIR:-.}/php-apache
        target: /php-apache
      - type: bind
        source: ${SHARE_DIR:-./workspace_share}
        target: /share
    environment:
      ENV LANGUAGE: ja_JP.UTF-8
      ENV LANG: ja_JP.UTF-8
      ENV LC_ALL: ja_JP.UTF-8
      EDITOR: code
      NPM_CONFIG_USERCONFIG: ${NPM_CONFIG_USERCONFIG:-/home/node/.npmrc}

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    # network_mode: service:dvc-wordpress を使うと `hostname:` は指定できない。
    network_mode: service:dvc-wordpress
    command: >
      sh -c "printf 'events { worker_connections 1024; }
      stream {
          server { listen 5080; proxy_pass php-apache-adminer:8080; }
          server { listen 8080; proxy_pass php-apache:80; }
          server { listen 13306; proxy_pass php-apache-mysql:3306; }
      }' > /tmp/nginx_stream.conf && nginx -c /tmp/nginx_stream.conf -g 'daemon off;'"
    depends_on:
      php-apache-adminer:
        condition: service_started
      php-apache:
        condition: service_started
      php-apache-mysql:
        condition: service_healthy
    # wordpress のネットワークスタックを共有しているため、`networks:` の指定なし
    # nginx-proxy サービス自身は、dvc-net に直接参加する必要なし

  php-apache:
    volumes:
      - type: volume
        source: workspace-data
        target: /home/node/workspace
    networks:
      dvc-net:
    # 必要がある場合に有効化
    # extra_hosts:
    #  # aliases は Docker 内部の DNS に登録されてしまうので使えない。
    #  - "dev.internal:127.0.0.1"
    ports:
      - ${PHP_IP_PORT:-127.0.0.1:8080}:80
      - ${PHP_BUILT_IN_IP_PORT:-127.0.0.1:10080}:10080

  php-apache-mysql:
    networks:
      dvc-net:
        aliases:
          - db
    ports:
      - ${MYSQL_IP_PORT:-127.0.0.1:13306}:3306

  php-apache-adminer:
    networks:
      dvc-net:
    ports:
      - ${ADMINER_IP_PORT:-127.0.0.1:5080}:8080

  php-apache-nginx-proxy:
    image: nginx:alpine
    container_name: php-apache-nginx-proxy
    # network_mode: service:php-apache を使うと `hostname:` は指定できない。
    network_mode: service:php-apache
    command: >
      sh -c "printf 'events { worker_connections 1024; }
      stream {
          server { listen 25; proxy_pass mailpit:1025; }
      }' > /tmp/nginx_stream.conf && nginx -c /tmp/nginx_stream.conf -g 'daemon off;'"
    depends_on:
      mailpit:
        condition: service_started

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    hostname: dev.internal
    ports:
      # Mailpit Web UI
      - "127.0.0.1:8025:8025"
      # Mailpit SMTP
      - "127.0.0.1:1025:1025"
    networks:
      dvc-net:
    # 送信用メールサーバの設定は php-apache の `php.ini` にある次の指定で有効化されている
    #
    # ```ini
    # [mail function]
    # SMTP = localhost
    # smtp_port = 25
    # ```

volumes:
  node-local-share-mise:
    name: dvc-wordpress-node-local-share-mise
  node-local-state-mise:
    name: dvc-wordpress-node-local-state-mise
  workspace-data:
    name: dvc-wordpress-home-node-workspace-data
  vscode-server-extensions:
    name: dvc-wordpress-vscode-server-extensions
  php-apache-data:
    name: dvc-wordpress-php-apache-data
    external: true
  php-apache-mysql-data:
    name: dvc-wordpress-php-apache-mysql-data
    external: true

networks:
  dvc-net:
    name: dvc-wordpress-net

include:
  - ./php-apache/php-apache-core/compose.yaml
